version: "3"
services:
  recv_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/routing/recv_hlc
    networks:
      - hidden-lake
  send_hls:
    build:
      context: ./../../../../
      dockerfile: cmd/hls/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/routing/send_hls
    ports:
      - 7572:7572
    networks:
      - hidden-lake
  middle_hlt_1:
    build:
      context: ./../../../../
      dockerfile: cmd/hlt/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/routing/middle_hlt_1
    networks:
      - hidden-lake
  middle_hlt_2:
    build:
      context: ./../../../../
      dockerfile: cmd/hlt/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/routing/middle_hlt_2
    networks:
      - hidden-lake
  middle_hlt_3:
    build:
      context: ./../../../../
      dockerfile: cmd/hlt/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/remoter/routing/middle_hlt_3
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
