version: "3"
services:
  node1_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/filesharer/routing/node1_hlf
    ports:
      - 8572:8572
      - 8080:8080
    networks:
      - hidden-lake
  node2_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/filesharer/routing/node2_hlf
    ports:
      - 7070:7070
    networks:
      - hidden-lake
  middle_hla_tcp_1:
    build:
      context: ./../../../
      dockerfile: cmd/hla_tcp/Dockerfile
    environment:
      - SERVICE_PATH=examples/filesharer/routing/middle_hla_tcp_1
    networks:
      - hidden-lake
  middle_hla_tcp_2:
    build:
      context: ./../../../
      dockerfile: cmd/hla_tcp/Dockerfile
    environment:
      - SERVICE_PATH=examples/filesharer/routing/middle_hla_tcp_2
    networks:
      - hidden-lake
  middle_hla_tcp_3:
    build:
      context: ./../../../
      dockerfile: cmd/hla_tcp/Dockerfile
    environment:
      - SERVICE_PATH=examples/filesharer/routing/middle_hla_tcp_3
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
