version: "3"
services:
  node1_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_NETWORK=oi4r9NW9Le7fKF9d
      - SERVICE_PATH=examples/messenger/prod_test/node1_hlm
    ports:
      - 8080:8080
  node2_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_NETWORK=oi4r9NW9Le7fKF9d
      - SERVICE_PATH=examples/messenger/prod_test/node2_hlm
    ports:
      - 7070:7070
      - 7572:7572
