version: "3"
services:
  node1_hln:
    build:
      context: ./../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_NETWORK=oi4r9NW9Le7fKF9d
      - SERVICE_PATH=examples/notifier/simple/node1_hln
    ports:
      - 8561:8561
    networks:
      - hidden-lake
  node2_hln:
    build:
      context: ./../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_NETWORK=oi4r9NW9Le7fKF9d
      - SERVICE_PATH=examples/notifier/simple/node2_hln
    ports:
      - 7561:7561
      - 7572:7572
    networks:
      - hidden-lake
  node3_hln:
    build:
      context: ./../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_NETWORK=oi4r9NW9Le7fKF9d
      - SERVICE_PATH=examples/notifier/simple/node3_hln
    ports:
      - 6561:6561
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
