version: "3"
services:
  service:
    build:
      context: ./../../../../../
      dockerfile: cmd/hla/common/service/Dockerfile
    environment:
      - SERVICE_ADDR=:6060
      - LOG_ENABLED=false
    networks:
      - hidden-lake
  node1_hlc:
    build:
      context: ./../../../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/filesharer/secret_channel/common/node1_hlf
    ports:
      - 8572:8572
      - 8080:8080
    networks:
      - hidden-lake
  node2_hlc:
    build:
      context: ./../../../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/filesharer/secret_channel/common/node2_hlf
    ports:
      - 7070:7070
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
