version: "3"
services:
  node1_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/messenger/routing/node1_hlm
    ports:
      - 8080:8080
    networks:
      - hidden-lake
  node2_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/messenger/routing/node2_hlm
    ports:
      - 7070:7070
      - 7572:7572
    networks:
      - hidden-lake
  middle_hla_tcp_1:
    build:
      context: ./../../../../
      dockerfile: cmd/hla_tcp/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/messenger/routing/middle_hla_tcp_1
    networks:
      - hidden-lake
  middle_hla_tcp_2:
    build:
      context: ./../../../../
      dockerfile: cmd/hla_tcp/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/messenger/routing/middle_hla_tcp_2
    networks:
      - hidden-lake
  middle_hla_tcp_3:
    build:
      context: ./../../../../
      dockerfile: cmd/hla_tcp/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/messenger/routing/middle_hla_tcp_3
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
