version: "3"
services:
  recv_hlc:
    build:
      context: ./../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_NETWORK=oi4r9NW9Le7fKF9d
      - SERVICE_PATH=examples/pinger/prod_test/recv_hlc
    networks:
      - hidden-lake
  send_hls:
    build:
      context: ./../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_NETWORK=oi4r9NW9Le7fKF9d
      - SERVICE_PATH=examples/pinger/prod_test/send_hls
    ports:
      - 7572:7572
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
