version: "3"
services:
  middle_hla_tcp:
    build:
      context: ./../../../../
      dockerfile: cmd/hla_tcp/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/messenger/group/middle_hla_tcp
    networks:
      - hidden-lake
  node1_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/messenger/group/node1_hlm
    ports:
      - 8080:8080
    networks:
      - hidden-lake
  node2_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/messenger/group/node2_hlm
    ports:
      - 7070:7070
      - 7572:7572
    networks:
      - hidden-lake
  node3_hlc:
    build:
      context: ./../../../../
      dockerfile: cmd/hlc/Dockerfile
    environment:
      - SERVICE_PATH=examples/anonymity/messenger/group/node3_hlm
    ports:
      - 6060:6060
    networks:
      - hidden-lake
networks:
  hidden-lake:
    driver: bridge
