name: build

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - name: Applications installing...
      run: sudo apt-get update && sudo apt-get install -y wget gcc make git
    - name: Set up Go 1.23
      uses: actions/setup-go@v2
      with:
          go-version: 1.23.0
    - name: Go-peer version
      run: export PATH=$PATH:$(go env GOPATH)/bin && go version
    - name: Hidden-Lake downloading...
      run: git clone --depth=1 https://github.com/number571/hidden-lake.git
    - name: Hidden-Lake deps installing...
      run: export PATH=$PATH:$(go env GOPATH)/bin && make install-deps -C hidden-lake
    - name: Hidden-Lake lint/test running...
      run: export PATH=$PATH:$(go env GOPATH)/bin && make -C hidden-lake
