name: build

on:
  push:
    branches: [ "master", "develop" ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4
    - name: Set up Go 1.23
      uses: actions/setup-go@v2
      with:
          go-version: 1.23.0
    - name: Applications installing...
      run: sudo apt-get update && sudo apt-get install -y wget
    - name: Hidden-Lake deps installing...
      run: export PATH=$PATH:$(go env GOPATH)/bin && make install-deps
    - name: Hidden-Lake lint/test running...
      run: export PATH=$PATH:$(go env GOPATH)/bin && make
